feat: new aggregate snapshotting + migration event and command
Informatievlaanderen/parcel-registry pull request #462
Opened 2022-11-18 13:55 UTC by jvandaal

2022-11-18 14:03 UTC, jvandaal commented on src/ParcelRegistry/Legacy/CommandHandlerModules.cs
> +            containerBuilder.RegisterType<FixGrar1637ProvenanceFactory>().AsSelf();
Added them here based upon https://github.com/Informatievlaanderen/building-registry/blob/main/src/BuildingRegistry/Legacy/CommandHandlerModules.cs#L18-L20

Don't know how they were previously resolved (and if there's a conflict now)?

2022-11-18 14:10 UTC, jvandaal commented on src/ParcelRegistry/Parcel/ValueObjects/VbrCaPaKey.cs
> +        private static readonly Guid Namespace = new Guid("28068113-774a-4f6f-8264-9ddb39095bd4");
@ArneD we have copy-pasted this class. So the Guid is the same as in Legacy. Should it be the same as in legacy?

2022-11-18 14:20 UTC, ArneD commented on src/ParcelRegistry/Parcel/Commands/MigrateParcel.cs
> +            IEnumerable<AddressPersistentLocalId> addressPersistentLocalIds,
Yes!

2022-11-18 14:29 UTC, ArneD requested changes

2022-11-18 14:29 UTC, ArneD commented on src/ParcelRegistry/Parcel/SnapshotContainerV2.cs
> +    {
remove empty line => `{ }`

2022-11-18 14:34 UTC, jvandaal commented on src/ParcelRegistry/Parcel/ValueObjects/VbrCaPaKey.cs
> +        private static readonly Guid Namespace = new Guid("28068113-774a-4f6f-8264-9ddb39095bd4");
Done.

2022-11-18 14:35 UTC, jvandaal commented on src/ParcelRegistry/Parcel/SnapshotContainerV2.cs
> +    {
Done

2022-11-18 14:41 UTC, ArneD approved these changes

2022-11-18 14:41 UTC, merged

2022-11-18 14:42 UTC, jvandaal commented on src/ParcelRegistry/Legacy/CommandHandlerModules.cs
> +            containerBuilder.RegisterType<FixGrar1637ProvenanceFactory>().AsSelf();
Just saw that ParcelCommandHandlerModule is also created manually in import. Didn't notice that before.

2022-11-24 19:26 UTC, basisregisters-vlaanderen commented
:tada: This PR is included in version 4.2.0 :tada:

The release is available on [GitHub release](https://github.com/Informatievlaanderen/parcel-registry/releases/tag/v4.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: