feat: Mark as migrated
Informatievlaanderen/parcel-registry pull request #463
Opened 2022-11-21 08:16 UTC by pgallik

2022-11-21 08:24 UTC, lvermeulen approved these changes

2022-11-21 08:28 UTC, ArneD requested changes

2022-11-21 08:28 UTC, ArneD commented on src/ParcelRegistry/Parcel/ValueObjects/VbrCaPaKey.cs
> +namespace ParcelRegistry.Parcel
why is there a new valueobject, I thought we moved it to higher level for reuse.

2022-11-21 09:00 UTC, ArneD approved these changes

2022-11-21 09:00 UTC, merged

2022-11-24 19:26 UTC, basisregisters-vlaanderen commented
:tada: This PR is included in version 4.2.0 :tada:

The release is available on [GitHub release](https://github.com/Informatievlaanderen/parcel-registry/releases/tag/v4.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: