feat: add VbrCaPaKey to aggregate state
Informatievlaanderen/parcel-registry pull request #472
Opened 2022-11-22 16:07 UTC by emalfroy

2022-11-23 15:38 UTC, ArneD commented on src/ParcelRegistry.Projections.Extract/ParcelExtract/ParcelExtractV2.cs
> +        public string? CaPaKey { get; set; }
Aren't these required?

2022-11-23 15:39 UTC, ArneD commented on src/ParcelRegistry.Projections.Extract/ParcelExtract/ParcelExtractV2Projections.cs
> +        private const string InUse = "Gerealiseerd";
Maybe rename to `Realized`

2022-11-23 16:29 UTC, ArneD requested changes
Legacy projection tests?

2022-11-24 13:19 UTC, jvandaal commented on src/ParcelRegistry.Projections.Extract/ParcelExtract/ParcelExtractV2.cs
> +        public string? CaPaKey { get; set; }
They are.

2022-11-24 13:20 UTC, jvandaal commented on src/ParcelRegistry.Projections.Extract/ParcelExtract/ParcelExtractV2Projections.cs
> +        private const string InUse = "Gerealiseerd";
Changed

2022-11-24 13:20 UTC, jvandaal commented on src/ParcelRegistry.Projections.Legacy/LegacyContext.cs
> +    using ParcelDetailListViewCount = ParcelDetail.ParcelDetailListViewCount;
Removed.

2022-11-24 13:20 UTC, jvandaal commented on src/ParcelRegistry.Projector/Infrastructure/Startup.cs
> +                            //    tags: new[] {DatabaseTag, "sql", "sqlserver"});
Undone

2022-11-24 15:06 UTC, ArneD approved these changes

2022-11-24 15:07 UTC, merged

2022-11-24 19:26 UTC, basisregisters-vlaanderen commented
:tada: This PR is included in version 4.2.0 :tada:

The release is available on [GitHub release](https://github.com/Informatievlaanderen/parcel-registry/releases/tag/v4.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: